services:
  db:
    image: postgis/postgis:16-3.4
    container_name: geoasset_db

    environment:
      POSTGRES_USER: geouser
      POSTGRES_PASSWORD: geopass
      POSTGRES_DB: geoasset

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: