"""add owner_id to assets

Revision ID: 6276557cc0d1
Revises: 6afa7c563dca
Create Date: 2026-07-17 17:37:19.038165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6276557cc0d1'
down_revision: Union[str, Sequence[str], None] = '6afa7c563dca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'assets', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_column('assets', 'owner_id')
    # ### end Alembic commands ###
